const data = {
  products: [
    {
      name: '10" Marijuana Leaf Print Water Pipe',
      slug: '10" Marijuana Leaf Print Water Pipe',
      category: "products",
      image: "images/glass-bong-ganja.webp",
      price: 50,
      countInStock: 10,
      brand: "Unbranded",
      rating: 4.5,
      numReviews: 10,
      description: "This product really products.",
    },
    {
      name: "Chameleon-glass-atmosphere-series-fumed",
      slug: "Chameleon-glass-atmosphere-series-fumed",
      category: "products",
      image:
        "images/chameleon-glass-atmosphere-series-fumed-bong-chameleon-glass-4114447171629_600x.webp",
      price: 85,
      countInStock: 0,
      brand: "Chameleon",
      rating: 4.5,
      numReviews: 22,
      description: "This product really products.",
    },
    {
      name: '8" silcon knot with recycler',
      slug: '8" silcon knot with recycler',
      category: "products",
      image: "images/glass-bong-glass-water-pipe.jpg",
      price: 50,
      countInStock: 25,
      brand: "Unbranded",
      rating: 2.5,
      numReviews: 14,
      description: "This product really products.",
    },
    {
      name: '10" Lookah Heady',
      slug: '10" Lookah Heady',
      category: "products",
      image: "images/LookahHeady.jpg",
      price: 130,
      countInStock: 10,
      brand: "Lookah",
      rating: 5,
      numReviews: 10,
      description: "This product really products.",
    },
  ],
};
export default data;
